[build]
builder = "nixpacks"

[deploy]
startCommand = "node src/server-multistream.js"
healthcheckPath = "/health"

[variables]
PORT = "3000"
BOT_SECRET = "replaybet-secret-2026"
NODE_ENV = "production"
